import 'package:sqflite/sqflite.dart';
import 'package:suchigo_app/core/storage/local_db.dart';
import 'package:suchigo_app/core/storage/local_db_tables.dart';

/// Represents the overall health status of the local database.
enum DatabaseHealthStatus {
  healthy,
  degraded,
  failed,
}

/// A comprehensive report generated by [DatabaseHealthService].
class DatabaseHealthReport {
  final DatabaseHealthStatus status;
  final String message;
  final List<String> missingTables;
  final List<String> missingIndexes;

  const DatabaseHealthReport({
    required this.status,
    required this.message,
    this.missingTables = const [],
    this.missingIndexes = const [],
  });
}

/// Service responsible for verifying the integrity of the SQLite database.
///
/// Executes `PRAGMA` and `sqlite_master` queries to ensure tables and indexes
/// exist exactly as defined in `LocalDbTables`.
/// Run this before Stage 3 bootstrapping to ensure storage is ready.
class DatabaseHealthService {
  final LocalDb db;

  DatabaseHealthService({required this.db});

  /// Inspects the database and generates a [DatabaseHealthReport].
  Future<DatabaseHealthReport> verifyHealth() async {
    final database = db.internalDb;
    
    if (database == null || !database.isOpen) {
      return const DatabaseHealthReport(
        status: DatabaseHealthStatus.failed,
        message: 'Database is not open or not initialized.',
      );
    }

    try {
      final tablesQuery = await database.rawQuery(
        "SELECT name FROM sqlite_master WHERE type='table'",
      );
      final existingTables = tablesQuery.map((row) => row['name'] as String).toSet();

      final indexesQuery = await database.rawQuery(
        "SELECT name FROM sqlite_master WHERE type='index'",
      );
      final existingIndexes = indexesQuery.map((row) => row['name'] as String).toSet();

      final requiredTables = [
        LocalDbTables.users,
        LocalDbTables.bookings,
        LocalDbTables.trackingCache,
        LocalDbTables.bills,
        LocalDbTables.syncQueue,
      ];

      // SQLite auto-generates some indexes (e.g. for UNIQUE), but we specifically check our explicit ones.
      final requiredIndexes = [
        'idx_users_lookup',
        'idx_bookings_user_status',
        'idx_tracking_cache_booking',
        'idx_bills_booking',
        'idx_sync_queue_lookup',
      ];

      final missingTables = requiredTables.where((t) => !existingTables.contains(t)).toList();
      final missingIndexes = requiredIndexes.where((idx) => !existingIndexes.contains(idx)).toList();

      if (missingTables.isEmpty && missingIndexes.isEmpty) {
        final versionResult = await database.rawQuery('PRAGMA user_version');
        final version = Sqflite.firstIntValue(versionResult) ?? 0;
        if (version != LocalDbTables.version) {
          return DatabaseHealthReport(
            status: DatabaseHealthStatus.degraded,
            message: 'Schema version mismatch (Found: $version, Expected: ${LocalDbTables.version}).',
          );
        }

        return const DatabaseHealthReport(
          status: DatabaseHealthStatus.healthy,
          message: 'Database is healthy. All tables and indexes verified.',
        );
      }

      final status = missingTables.isNotEmpty
          ? DatabaseHealthStatus.failed
          : DatabaseHealthStatus.degraded;

      return DatabaseHealthReport(
        status: status,
        message: 'Database schema verification failed.',
        missingTables: missingTables,
        missingIndexes: missingIndexes,
      );
    } catch (e) {
      return DatabaseHealthReport(
        status: DatabaseHealthStatus.failed,
        message: 'Health check threw an exception: $e',
      );
    }
  }
}
