// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgq6BCS9mWB_BaodwIUTcU67s94u1_1M',
    appId: '1:20744177268:web:922406f5e56d1f7eaab321',
    messagingSenderId: '20744177268',
    projectId: 'suchigo-16811',
    authDomain: 'suchigo-16811.firebaseapp.com',
    storageBucket: 'suchigo-16811.firebasestorage.app',
    measurementId: 'G-CPY8KL48R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyUTuH81Dh9vx6NCGKBBFY_YN2mEWqY8',
    appId: '1:20744177268:android:b257c3ca07cc105faab321',
    messagingSenderId: '20744177268',
    projectId: 'suchigo-16811',
    storageBucket: 'suchigo-16811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CgUlFBdEIcLc2NFI73LqXEGfLWabXh8',
    appId: '1:20744177268:ios:a0e88591a76951dfaab321',
    messagingSenderId: '20744177268',
    projectId: 'suchigo-16811',
    storageBucket: 'suchigo-16811.firebasestorage.app',
    iosBundleId: 'com.example.suchigoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CgUlFBdEIcLc2NFI73LqXEGfLWabXh8',
    appId: '1:20744177268:ios:a0e88591a76951dfaab321',
    messagingSenderId: '20744177268',
    projectId: 'suchigo-16811',
    storageBucket: 'suchigo-16811.firebasestorage.app',
    iosBundleId: 'com.example.suchigoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxgq6BCS9mWB_BaodwIUTcU67s94u1_1M',
    appId: '1:20744177268:web:14ddddc5f4ff45d6aab321',
    messagingSenderId: '20744177268',
    projectId: 'suchigo-16811',
    authDomain: 'suchigo-16811.firebaseapp.com',
    storageBucket: 'suchigo-16811.firebasestorage.app',
    measurementId: 'G-N240FDHC3E',
  );
}
